[package]
authors = ["Sergei Gureev <bemyak@pm.me>"]
edition = "2018"
name    = "squarifier"
version = "0.2.0"

[profile.release]
lto   = true
panic = 'abort'

[dependencies]
async-std = { version = "1.6", features = ["attributes"] }
base64    = "0.13"
image     = "0.23"
surf      = "2.1"
tide      = "0.14"
http-types = "2.7"
