[package]
authors = ["Sergei Gureev <bemyak@pm.me>"]
edition = "2018"
name    = "squarifier"
version = "0.1.0"

[profile.release]
lto   = true
panic = 'abort'

[dependencies]
async-std = { version = "1.6", features = ["attributes"] }
base64    = "0.12"
image     = "0.23"
surf      = "1.0"
tide      = "0.13"
